// Provides committed, non-sensitive fixtures for provider-neutral chat previews.
import type { ChatPreviewFixture, PortableAction, PortableNotification } from "./contracts";

const openMgr = (label: string): PortableAction => ({ id: "open_mgr", label, enabled: true });
const notification = (value: PortableNotification): PortableNotification => value;

export const CHAT_PREVIEW_FIXTURES: readonly ChatPreviewFixture[] = [
  {
    id: "settings-disconnected",
    surface: "settings",
    title: "Chat notifications",
    eyebrow: "Back · Settings · Chat",
    status: { label: "Slack · Not connected", tone: "neutral" },
    fields: [
      { label: "Projection", value: "Bring today’s assigned, due and overdue work into chat. MGR remains the source of truth." },
      { label: "Preview surfaces", value: "App Home · personal DM · team digest" },
    ],
    items: [],
    actions: [{ id: "open_mgr", label: "Connect Slack", enabled: true }],
  },
  {
    id: "settings-active",
    surface: "settings",
    title: "Chat",
    eyebrow: "Back · Settings",
    status: { label: "Slack · Demo Brewing · Connected · scopes healthy", tone: "healthy" },
    fields: [
      { label: "Operations channel", value: "#mgr-operations · private" },
      { label: "Quiet hours", value: "9:00 PM–6:00 AM · brewery time" },
      { label: "Reading overdue after", value: "24 hours · Today + chat" },
      { label: "Preview · App Home", value: "4 current work reasons · fixture data" },
    ],
    items: [],
    actions: [openMgr("Open preview"), { id: "edit_preferences", label: "Disable", enabled: true }],
  },
  {
    id: "link",
    surface: "app_home",
    title: "Your MGR work",
    eyebrow: "Slack · MGR · App Home",
    fields: [
      { label: "Link", value: "Link your account to see only work your current brewery role permits." },
      { label: "Privacy", value: "No customer contacts, prices or notes are posted here" },
    ],
    items: [],
    actions: [openMgr("Link MGR account")],
  },
  {
    id: "app-home",
    surface: "app_home",
    title: "Today · 4 waiting",
    eyebrow: "Slack · MGR · App Home · Refresh",
    fields: [],
    items: [
      notification({ reason: "submitted_order", urgency: "attention", subject: { type: "order", id: "order-0231", safeLabel: "ORD-0231" }, title: "Review submitted order", detail: "requested Thu · sales", dueAt: "2026-09-03T09:00:00.000Z", ownerClass: "sales", resolutionKey: "submitted-order:order-0231", actions: [openMgr("Open")] }),
      notification({ reason: "pick_due", urgency: "normal", subject: { type: "order", id: "order-0235", safeLabel: "ORD-0235" }, title: "Pick due", detail: "ships Fri · warehouse", dueAt: "2026-09-04T09:00:00.000Z", ownerClass: "warehouse", resolutionKey: "pick-due:order-0235", actions: [openMgr("Open")] }),
      notification({ reason: "delivery_next", urgency: "normal", subject: { type: "delivery", id: "route-a-next", safeLabel: "Route A · next stop" }, title: "Next stop", detail: "assigned to you · 9:30 AM", dueAt: "2026-09-04T09:30:00.000Z", ownerClass: "driver", resolutionKey: "delivery-next:route-a-next", actions: [openMgr("Open")] }),
      notification({ reason: "fermentation_reading_overdue", urgency: "attention", subject: { type: "occupancy", id: "fv2", safeLabel: "FV2 · reading overdue" }, title: "Reading overdue", detail: "last reading 26 h ago · brewer", dueAt: "2026-09-03T07:00:00.000Z", ownerClass: "brewer", resolutionKey: "fermentation-reading-overdue:fv2", actions: [openMgr("Open")] }),
    ],
    actions: [openMgr("Open Today in MGR"), { id: "refresh", label: "Refresh", enabled: true }],
  },
  {
    id: "personal-dm",
    surface: "direct_message",
    title: "ORD-0235",
    eyebrow: "Slack · MGR · Direct message",
    status: { label: "Pick due · assigned to you", tone: "attention" },
    fields: [
      { label: "Requested ship date", value: "Fri 9/4" },
      { label: "What to do", value: "Open the pick flow in MGR" },
    ],
    items: [notification({ reason: "pick_due", urgency: "attention", subject: { type: "order", id: "order-0235", safeLabel: "ORD-0235" }, title: "Pick due", detail: "assigned to you", dueAt: "2026-09-04T09:00:00.000Z", ownerClass: "warehouse", resolutionKey: "pick-due:order-0235", actions: [openMgr("Open pick in MGR"), { id: "snooze", label: "Snooze", enabled: true }, { id: "mute_reason", label: "Mute picks", enabled: true }] })],
    actions: [openMgr("Open pick in MGR"), { id: "snooze", label: "Snooze", enabled: true }, { id: "mute_reason", label: "Mute picks", enabled: true }],
  },
  {
    id: "team-digest",
    surface: "private_channel",
    title: "Morning operations · 6 waiting",
    eyebrow: "Slack · #mgr-operations · MGR",
    fields: [
      { label: "Submitted orders", value: "2 · need sales review" },
      { label: "Picks due", value: "2 · warehouse queue" },
      { label: "Assigned deliveries", value: "1 · next stops ready" },
      { label: "Fermentation readings", value: "1 · overdue" },
    ],
    items: [],
    actions: [openMgr("Open my MGR work")],
  },
  {
    id: "preferences",
    surface: "modal",
    title: "Notification preferences",
    eyebrow: "Close",
    fields: [
      { label: "Submitted orders", value: "On" },
      { label: "Picks due", value: "On" },
      { label: "Assigned deliveries", value: "On" },
      { label: "Fermentation readings", value: "On" },
      { label: "Quiet hours", value: "9:00 PM–6:00 AM" },
    ],
    items: [],
    actions: [{ id: "edit_preferences", label: "Save preferences", enabled: true }],
  },
  {
    id: "fermentation-gated",
    surface: "modal",
    title: "Record fermentation reading",
    eyebrow: "Close",
    status: { label: "Future phase only", tone: "attention" },
    fields: [
      { label: "Vessel", value: "FV2 · Hazy IPA" },
      { label: "Last reading", value: "26 h ago" },
      { label: "Reading", value: "4.2 °Plato · 68 °F" },
      { label: "Record reading", value: "Open this reading in MGR for now" },
    ],
    items: [],
    actions: [openMgr("Open in MGR")],
  },
  {
    id: "order-confirm-gated",
    surface: "modal",
    title: "Review order",
    eyebrow: "Close",
    status: { label: "Future phase only", tone: "attention" },
    fields: [
      { label: "Order", value: "ORD-0231 · 3 lines · requested Thu · Submitted" },
      { label: "Warning", value: "Hazy IPA · 16 oz case is 8 units short. Review allocations and restock in MGR." },
      { label: "Confirm order", value: "This order needs the full MGR review" },
    ],
    items: [],
    actions: [openMgr("Open order in MGR")],
  },
  {
    id: "reauthorization",
    surface: "settings",
    title: "Health",
    eyebrow: "Back · Chat",
    status: { label: "Slack authorization expired. No messages are being sent.", tone: "attention" },
    fields: [
      { label: "Last callback", value: "Today · 8:42 AM · Succeeded" },
      { label: "Last delivery", value: "Today · 8:43 AM · Succeeded" },
      { label: "Queued", value: "3 deliveries · Paused" },
    ],
    items: [],
    actions: [{ id: "open_mgr", label: "Reauthorize Slack", enabled: true }, { id: "edit_preferences", label: "Disable integration", enabled: true }],
  },
];
