// tests/rpc-allowlist.test.ts — every public RPC an authenticated user can
// execute, pinned by signature. A grant that is not listed here is a new
// product surface: add it in the same commit as its command, or it fails.
import { describe, expect, it } from "vitest";
import { sql } from "./helpers";

const AUTHENTICATED_RPCS = [
  "record_keg_event(uuid,uuid,keg_size,integer,keg_event_reason,uuid,uuid,uuid,text,uuid)",
  "save_route(uuid,uuid,text,date,uuid,text,text,jsonb,uuid)",
  "depart_route(uuid,uuid)",
  "return_route(uuid,uuid)",
  "update_keg_pool(uuid,uuid,text,uuid,integer,integer,boolean,uuid)",
  "create_keg_pool(uuid,text,keg_pool_kind,uuid,integer,integer,uuid)",
  "activate_chat_installation(uuid,text,text,text,text,text,text,jsonb)",
  "adjust_order_lines(uuid,jsonb,text,uuid)",
  "begin_chat_installation(uuid,text,text,text)",
  "begin_chat_reauthorization(uuid,text,text)",
  "cancel_order(uuid,text,uuid)",
  "clear_channel_price(uuid,uuid,uuid,uuid,uuid)",
  "close_packaging_run(uuid,uuid,numeric,jsonb,text,date,date,uuid,uuid,uuid)",
  "confirm_delivery(uuid,text,uuid)",
  "confirm_order(uuid,uuid)",
  "confirm_restock(uuid,uuid)",
  "consume_chat_link_proof(text)",
  "create_bin(uuid,uuid,text,uuid)",
  "create_credit_memo(uuid,jsonb,uuid,text,uuid)",
  "create_location(uuid,text,location_kind,uuid)",
  "create_order(uuid,order_kind,uuid,uuid,uuid,uuid,date,text,text,jsonb,uuid)",
  "create_purchase_order(uuid,uuid,date,text,jsonb,uuid)",
  "create_recipe(uuid,uuid,text,text,uuid)",
  "create_recipe_version(uuid,uuid,numeric,numeric,numeric,integer,numeric,text,jsonb,uuid)",
  "create_replenishment_order(uuid,uuid,jsonb,uuid)",
  "create_sku(uuid,uuid,uuid,text,text,uuid)",
  "create_stock_transfer(uuid,uuid,uuid,date,text,jsonb,uuid)",
  "delete_bin(uuid,uuid,uuid)",
  "delete_price_group(uuid,uuid,uuid)",
  "delete_sale_channel(uuid,uuid,uuid)",
  "disable_chat_installation(uuid)",
  "disconnect_chat_installation(uuid)",
  "draft_purchase_order_from_requirements(uuid,uuid[],uuid)",
  "find_chat_oauth_intent(text)",
  "get_today_items(uuid,timestamp with time zone)",
  "is_staff_of(uuid)",
  "mark_chat_installation_reauthorization(uuid,text)",
  "move_stock_bin(uuid,uuid,uuid,uuid,keg_size,numeric,uuid,uuid,text,uuid)",
  "my_brewery_ids()",
  "my_customer_ids()",
  "portal_availability(uuid)",
  "portal_brewery_rows()",
  "portal_create_order(uuid,uuid,uuid,text,text,jsonb,uuid)",
  "receive_purchase_order(uuid,uuid,uuid,uuid,date,jsonb,uuid)",
  "receive_stock_transfer(uuid,jsonb,uuid)",
  "reconcile_chat_installation(uuid,boolean,text)",
  "record_brew_day(uuid,uuid,uuid,numeric,date,uuid)",
  "record_cellar_transfer(uuid,uuid,uuid,numeric,numeric,uuid)",
  "record_fermentation_reading(uuid,uuid,timestamp with time zone,numeric,numeric,numeric,text,uuid)",
  "record_inventory_movement(uuid,uuid,uuid,uuid,numeric,movement_type,uuid,text,text,uuid)",
  "record_material_count(uuid,uuid,uuid,date,jsonb,uuid)",
  "record_pick(uuid,jsonb,uuid)",
  "record_repack(uuid,uuid,uuid,uuid,numeric,uuid,numeric,uuid)",
  "record_stock_transfer_pick(uuid,jsonb,uuid)",
  "record_submitted_order_occurrence(uuid)",
  "release_allocation(uuid,uuid)",
  "replace_format_bom(uuid,uuid,jsonb,uuid)",
  "replace_format_components(uuid,uuid,jsonb,uuid)",
  "resolve_short_pick(uuid,uuid,numeric,text,text,uuid)",
  "return_shipment(uuid,jsonb,uuid,text,uuid)",
  "schedule_batch(uuid,uuid,uuid,date,numeric,text,uuid)",
  "schedule_packaging_run(uuid,uuid,date,uuid,jsonb,uuid)",
  "send_purchase_order(uuid,uuid,text,uuid)",
  "set_brewery_gravity_unit(uuid,text,uuid)",
  "set_brewery_quiet_hours(uuid,time without time zone,time without time zone)",
  "set_my_gravity_unit(uuid,text,uuid)",
  "set_notification_destination(uuid,text)",
  "set_notification_preference(uuid,text,boolean,time without time zone,time without time zone,text)",
  "set_portal_fulfillment_source(uuid,uuid,uuid)",
  "set_channel_price(uuid,uuid,uuid,uuid,integer,uuid)",
  "set_standing_allocation(uuid,uuid,numeric,uuid)",
  "set_taproom_par(uuid,uuid,uuid,numeric,uuid)",
  "ship_order(uuid,jsonb,text,text,uuid,text)",
  "staff_role(uuid)",
  "submit_order(uuid,uuid)",
  "submit_stock_transfer(uuid,uuid)",
  "today_live_reasons()",
  "unlink_chat_user(uuid)",
  "update_bin(uuid,uuid,text,uuid)",
  "update_draft_order(uuid,uuid,date,text,text,jsonb,uuid)",
  "update_location(uuid,uuid,text,location_kind,uuid)",
  "update_packaging_run(uuid,uuid,uuid,jsonb,timestamp with time zone,uuid)",
  "upsert_brand(uuid,uuid,text,text,numeric,text,text,uuid,text,uuid)",
  "upsert_customer(uuid,uuid,text,customer_type,text,uuid,text,text,tax_treatment,uuid)",
  "upsert_format(uuid,uuid,text,format_basis,package_type,keg_size,integer,numeric,uuid)",
  "upsert_material(uuid,uuid,text,material_category,uom,uom,numeric,boolean,uuid,numeric,boolean,uuid)",
  "upsert_material_contract(uuid,uuid,uuid,uuid,numeric,integer,date,date,text,uuid)",
  "upsert_price_group(uuid,uuid,text,integer,integer,uuid)",
  "upsert_sale_channel(uuid,uuid,text,tax_treatment,uuid)",
  "upsert_ship_to(uuid,uuid,uuid,text,text,text,text,text,text,uuid)",
  "upsert_vendor(uuid,uuid,text,text,text,integer,text,boolean,uuid)",
  "upsert_vessel(uuid,uuid,text,vessel_kind,numeric,uuid)",
];

describe("authenticated RPC allowlist", () => {
  it("matches the public functions authenticated can execute", () => {
    const actual = sql(`
      select p.oid::regprocedure::text from pg_proc p
      where p.pronamespace = 'public'::regnamespace
        and has_function_privilege('authenticated', p.oid, 'execute')
        and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e')
      order by 1`);
    // same comparator on both sides: Postgres collation orders punctuation differently from JS
    expect([...actual].sort()).toEqual([...AUTHENTICATED_RPCS].sort());
  });
});
