// lib/mgr/screen-links.ts — the explorer's tap resolver: which screen a tap
// inside a drawn screen opens. Screens are static drawings, so the label is
// the link: a record's own `to` map wins, then the global rules here (labels
// and shell routes that always mean one screen), then an exact screen-name
// match — which already covers every back arrow, tab and "New order" style
// verb. Unresolved taps do nothing. Pure, so tests/screen-links.test.ts can
// walk the main flows without a DOM.
import { type Screen } from "@/components/mgr/screens";
import { screenByName } from "@/lib/mgr/screen-explorer";

/** The resolver's answer for a dismiss verb: leave this screen for the one before. */
export const BACK = "\u2190";

/** Labels (or label patterns) that mean one screen wherever they appear. */
export const TAPS: [string | RegExp, string][] = [
  ["Cancel", BACK],
  ["Close", BACK],
  ["Discard", BACK],
  ["Not now", BACK],
  ["Back", BACK],
  ["Keep", BACK],
  [/^ORD-\d+/, "Order"],
  [/^INV-\d+/, "Invoice"],
  [/^PO-\d+/, "Receive PO"],
  [/^(Hazy IPA|Pils|Stout) · /, "SKU detail"],
  [/^Review order\b/, "Review order"],
  [/^Place order\b/, "Order detail"],
  [/^Same as last week$/, "Review order"],
  ["Confirm", "Confirm order"],
  ["Confirm order", "Order"],
  ["Save draft", "Order"],
  ["Save customer", "Customer detail"],
  ["Save ship-to", "Customer detail"],
  ["Ship", "Ship and invoice"],
  ["Receive", "Receive PO"],
  ["Invite", "Invite portal user"],
  ["Resume", "Driver route"],
  ["Review", "SKU detail"],
  ["Reorder", "Shop"],
  ["Edit prices", "Price tiers"],
  ["Sign out", "Sign in"],
  ["Sign in", "Today"],
  ["Send reset link", "Set new password"],
  ["Save password", "Today"],
  ["Change password", "Set new password"],
  ["Understood", BACK],
  ["Use", BACK],
  [/^L-\d{6}-[A-Z]{2}$/, "Lot trace"],
  ["Ridgeline Tap Room", "Customer detail"],
  [/^(FV|BT|FB)\d/, "Vessel detail"],
  // Rules below were written from the coverage report (tests/tap-coverage.test.ts).
  [/^B-\d+/, "Brew day"],
  [/^RUN-\d+/, "Close packaging run"],
  ["Reading", "Fermentation reading"],
  ["Start", "Brew day"],
  ["Transfer", "Cellar transfer"],
  [/^Stop \d+ ·/, "Confirm delivery"],
  [/^Resume · Stop/, "Confirm delivery"],
  ["Swap", "Swap keg"],
  ["Kick", "Kick keg"],
  ["Tap", "Swap keg"],
  [/^Tap \d+ ·/, "Swap keg"],
  [/^(\d+|unnumbered)[A-Z]/, "Swap keg"],
  ["Shortfall", "Pars and allocation"],
  ["Choose who gets it", "Pars and allocation"],
  ["Count", "Cycle count"],
  ["Add material", "Material"],
  ["Add SKU", "SKU"],
  ["Taps", "Tap board"],
  ["Cellar", "Cellar map"],
  ["Kegs", "Keg fleet"],
  ["Import CSV", "Import"],
  ["Review history", "Keg event history"],
  ["Open balance", "Customer keg balance"],
  ["Open batch", "Brew day"],
  ["Fix registration", "State registration"],
  ["Guest cider", "POS mapping"],
  ["Record opening count", "Record movement"],
  [/^Route [A-Z]( · |$)/, "Route"],
  [/^TRF-\d+/, "Order"],
  [/^(Ridgeline|Al’s Bar|Teresa’s) · ORD-\d+/, "Pick"],
  [/^Unassigned · ORD-\d+/, "Order"],
  ["Cancel order", "Orders"],
  ["Done picking", "Order"],
  ["Save schedule", "Batches"],
  ["Record brew day", "Batches"],
  ["Schedule run", "Schedule packaging run"],
  ["Receive purchase order", "Receipt"],
  ["New route", "Route"],
  ["Save route plan", "Routes"],
  ["Depart route", "Return route"],
  ["Delivered", "Driver route"],
  ["New batch", "Schedule batch"],
  ["Bins", "Location bins"],
  ["Chat", "Chat settings"],
  ["Al\u2019s Bar", "Customer detail"],
  ["Teresa\u2019s", "Customer detail"],
  ["Add customer", "Customer detail"],
  ["Add location", "Location detail"],
  ["Maria Alvarez", "Team member"],
  ["Dave Chen", "Team member"],
  ["Ted", "Team member"],
  ["Sam Ortiz", "Team member"],
  ["wes@demobrewing.com", "Team member"],
  ["Ship-tos", "Ship-to form"],
  ["Portal users", "Invite portal user"],
  [/^CM-\d+/, "Invoice"],
  ["Re-push", "Invoice"],
  ["QuickBooks", "Accounting"],
  ["Fix", "Fix mapping"],
  ["Add brand", "Product"],
  ["Save brand", "Catalog"],
  ["\u00bd bbl keg", "SKU"],
  ["\u2159 bbl keg", "SKU"],
  ["case \u00b7 24\u00d716 oz", "SKU"],
  ["Add vendor", "Vendor"],
  ["YCH", "Vendor"],
  ["Country Malt", "Vendor"],
  ["CanSource", "Vendor"],
  ["Citra", "Material"],
  ["2-row", "Material"],
  ["Cans \u00b7 16 oz", "Material"],
  ["Add contract", "Contract"],
  [/^(YCH|Country Malt) · /, "Contract"],
  ["Create recipe", "Recipe"],
  [/^(Hazy IPA|Pils|Stout) v\d+$/, "Recipe"],
  [/^(January|February|March|April|May|June|July|August|September|October|November|December) \d{4}$/, "Monthly compliance"],
  ["Save filed snapshot", "Compliance months"],
  ["Ohio", "State registration"],
  ["Pennsylvania brewery license", "License"],
  ["Square Taproom", "Entity picker"],
  ["Square Warehouse", "Entity picker"],
  ["Square Events", "Entity picker"],
  ["\u201cHazy 16 oz draft\u201d", "Entity picker"],
  [/^(\d+ sales|\d+ refund) · /, "POS sale detail"],
  ["Add format", "Format"],
  ["Create price list", "Price tiers"],
  [/^Wholesale · /, "Price tiers"],
  ["Barrel-aged Stout \u00b7 \u00bd bbl keg", "Override"],
  ["Add override", "Override"],
  ["Walk-in", "Bin"],
  ["To-go fridge", "Bin"],
  ["Back to Today", "Today"],
  ["Go to Beer", "Beer"],
  ["Open as form", "Record movement"],
  ["Commit movement", "Movement recorded"],
  ["SKU / package", "Entity picker"],
  ["Materials in", "Materials on hand"],
  ["Back to sign in", "Sign in"],
  ["Request a new link", "Reset password"],
  ["Join Demo Brewing", "Today"],
  ["Draft purchase order", "Purchase orders"],
  ["Sept 12 packaging", "Packaging runs"],
  ["Reconnect QuickBooks", "Connect QuickBooks"],
  ["Customers missing an email", "Customers"],
  ["Question this invoice", "Question invoice"],
  ["Pay", "Pay invoice"],
  ["You \u00b7 buyer", "Portal Me"],
  ["Open mapping", "POS mapping"],
  ["Open count", "Weekly count"],
  [/^Weekly count · /, "Weekly count"],
  ["Map", "POS mapping"],
  [/^Square\W*QuickBooks connector$/, "Square \u2192 QuickBooks connector"],
  ["Connect Slack", "Chat settings"],
  ["Preview surfaces", "Chat settings"],
  ["Health", "Reauthorization"],
  ["Reauthorize Slack", "Chat settings"],
  ["Link accounts", "Today"],
];

/** Taps that act in place and lead nowhere — steppers, downloads, links out
 * to another product, add-a-row buttons — so the coverage test does not count
 * them as gaps. The explorer simply leaves them alone. */
export const INERT: (string | RegExp)[] = [
  "Reconcile 7 sales + 1 refund",
  "Main ship-to",
  "Dock ship-to",
  "+ add ingredient",
  "1 \u00b7 Add locations",
  "1 \u00b7 Review auto-reconciled losses",
  "2 \u00b7 Review generated figures",
  "2-row \u00b7 55 lb bags",
  "3 \u00b7 Confirm filed outside MGR",
  "4 \u00b7 Invite the team",
  "8/31 \u00b7 6:58 AM",
  "9/01 \u00b7 7:04 AM",
  "9/02 \u00b7 7:10 AM",
  "Acquired",
  "Add bin",
  "Add channel",
  "Add keg pool",
  "Add stop",
  "Adjust selected",
  "August 31, 2027",
  "Avery Stone",
  "Bank transfer (ACH)",
  "Buyer asked about this invoice",
  "Card",
  "Casey Lin",
  "Change",
  "Citra \u00b7 44 lb boxes",
  "Complete batch",
  "Create recipe version",
  "Current state",
  "Decrease",
  "Delivery enabled",
  "Demo Brewing LLC",
  "Demo Brewing",
  "Deposit refund",
  "Disable integration",
  "Disable",
  "Download PDF",
  "Due",
  "Found \u00b7 Al\u2019s Bar",
  "Hazy \u00b7 \u00bd bbl keg",
  "Import 2 customer rows",
  "Increase",
  "Invite staff",
  "Keg deposits held",
  "Last delivery",
  "Last message from Slack",
  "Lost \u00b7 Al\u2019s Bar",
  "Mark answered",
  "Morgan Reed",
  "Open in QuickBooks",
  "Owned \u00bd bbl",
  "Owned \u2159 bbl",
  "PA / OH excise",
  "Paid",
  "Post opening balances",
  /^Preview · (App Home|Personal DM|Team digest|Preferences)$/,
  "Print labels",
  "Print pick sheet",
  "Print trace",
  "Publish changes",
  "Push invoice to QuickBooks Online",
  "Queued",
  "QuickBooks Payments",
  "Reason",
  "Recent \u00b7 Kolsch tapped",
  "Recent \u00b7 Saison swapped in",
  "Record inventory correction",
  "Release",
  "Retired",
  "Returned \u00b7 Ridgeline",
  "Reverse a movement",
  "Rice hulls \u00b7 50 lb",
  "Role",
  "Save brewery",
  "Save item mapping",
  "Save keg pool",
  "Save location mapping",
  "Save vessel",
  "Send staff invite",
  "September 3, 2026",
  "September 4, 2026",
  "Ship-to \u00b7 requested date",
  "Ships from",
  "Skip",
  "Slack \u00b7 Demo Brewing",
  "Slack",
  "Square Taproom \u00b7 9/02 8:14 PM",
  "Square \u00b7 Demo Brewing LLC",
  "Status",
  "Sync Square sales",
  "Taproom standing",
  "Totals",
  "Transfer to",
  "Unlink",
  "Pay invoice",
  "Email me a link",
  "Default ship-to",
  "Active",
  "Sell while taproom stock remains",
  /^(January|February|March|April|May|June|July|August|September|October|November|December) \d{1,2}, \d{4}$/,
  "Reset to format price",
  "Switch",
  "Reload",
  "Already swapped",
  "Check",
  "Retry",
  "Retry 1 waiting",
  "Discard 4 queued writes",
  "Ridgeline Contract Brewing",
  "Keg deposit",
  "Hazy · cans (case of 24)",
  "16 oz can",
  "Can end",
  "Case tray",
  "Edit",
  "Replace BOM",
  "\u201cHow much Hazy can I promise Friday?\u201d",
];

/** Inside the portal shell the same chrome means the buyer's screens. */
export const PORTAL: Record<string, string> = { Me: "Portal Me", "Sign out": "Portal sign in", Invoices: "Invoice history", Orders: "Order history", Order: "Shop", Account: "Account" };

/** Shell links by route (lib/mgr/nav.ts): the tab bar, the rail and its children. */
export const ROUTES: Record<string, string> = {
  "/": "Today",
  "/inventory": "Finished goods",
  "/inventory#taproom": "Taproom",
  "/inventory#taps": "Tap board",
  "/inventory#cellar": "Cellar map",
  "/inventory#materials": "Materials on hand",
  "/inventory#kegs": "Keg fleet",
  "/orders": "Orders",
  "/pick": "Pick sheet",
  "/replenishment": "Pars and allocation",
  "/orders#batches": "Batches",
  "/orders#packaging": "Packaging runs",
  "/orders#purchase-orders": "Purchase orders",
  "/orders#deliveries": "Routes",
  "/invoices": "Invoices",
  "/catalog": "Catalog",
  "/catalog#menu": "Menu",
  "/customers": "Customers",
  "/pricing": "Price lists",
  "/catalog#recipes": "Recipes",
  "/invoices#compliance": "Compliance months",
  "/orders#planning": "Planning",
  "/settings/team#import": "Import",
  "/settings/team": "Settings",
  "/portal": "Shop",
  "/portal/orders": "Order history",
  "/portal/invoices": "Invoice history",
  "/portal/account": "Account",
};

/** A TAPS or INERT key against a label: exact for a string, a test for a pattern. */
export const matches = (k: string | RegExp, label: string) => (typeof k === "string" ? k === label : k.test(label));
export const isInert = (label: string) => INERT.some((k) => matches(k, label.trim()));
const isPortalSide = (name: string) => {
  const s = screenByName(name)?.[1];
  return Boolean(s && (s.portal || s.surface === "entry"));
};

/** `to` is an explicit target on the element (E.link's data-to) and wins outright.
 * Inside the portal a rule that lands on a staff screen is no rule: the buyer
 * has no staff vocabulary, so the tap acts in place instead. */
export function resolveTap(screen: Screen, label: string, href?: string | null, to?: string | null): string | undefined {
  if (to) return to;
  const l = label.trim();
  if (screen.to?.[l]) return screen.to[l];
  if (screen.portal && PORTAL[l]) return PORTAL[l];
  const guard = (name: string | undefined) => (screen.portal && name && name !== BACK && !isPortalSide(name) ? undefined : name);
  if (href && ROUTES[href]) return guard(ROUTES[href]);
  for (const [k, name] of TAPS) if (matches(k, l)) return guard(name);
  return screenByName(l) ? guard(l) : undefined;
}
